import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { LoginForm } from "../components";
import { useUserContext } from "../context/user.context";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  const user = useUserContext()

  if(!user) {
    return <LoginForm />
  }

  return (
    <>
      <Head>
        <title>eGarage | Making your next garage search easier</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="" />
      </Head>

      <Link href="garages/new">Create a garage</Link>
    </>
  );
};

export default Home;

